name: 01 - Building Blocks

on: 
  push:
  pull_request:
  schedule:
    - cron:'*/5 * * * *'
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps: 
    - name: Show Trigger
      run: echo "I've been triggered by a(n) ${{ github.event_name }} event."
