name: 04 - Using Actions

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencites
        run: npm ci
        working-directory: 04-using-actions/react-app

    #0  Checkout the code from the repository
    #1. Install depedencies of our react appication
    #2. Execute automated tests 
    #npx create-react-app -template typescript react-app
    #npm run start