name: 03 - using actions

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls

        
    #0  Checkout the code from the repository
    #1. Install depedencies of our react appication
    #2. Execute automated tests 
#npx create-react-app -template typescript react-app
#npm run start